<a href="https://colab.research.google.com/github/RohitKhobare/Data-Science-and-Big-Data-Analytics/blob/main/LA3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

print("Dataset Loaded Successfully!\n")

summary_stats = df.groupby('species')['sepal_length'].agg(['mean', 'median', 'min', 'max', 'std'])

print("--- Summary Statistics of Sepal Length grouped by Species ---")
display(summary_stats)
print("\n")

species_mapping = {'setosa': 0, 'versicolor': 1, 'virginica': 2}
numeric_species_list = df['species'].map(species_mapping).tolist()

print("--- Numeric List representing the Categorical Variable ---")
print(f"Total items in list: {len(numeric_species_list)}")
print("First 15 items in the list (representing the first 15 flowers, which are all setosa):")
print(numeric_species_list[:15])

Dataset Loaded Successfully!

--- Summary Statistics of Sepal Length grouped by Species ---

             mean  median  min  max       std
species
setosa      5.006     5.0  4.3  5.8  0.352490
versicolor  5.936     5.9  4.9  7.0  0.516171
virginica   6.588     6.5  4.9  7.9  0.635880

--- Numeric List representing the Categorical Variable ---
Total items in list: 150
First 15 items in the list (representing the first 15 flowers, which are all setosa):
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [2]:
statistical_details = df.groupby('species').describe()

print("--- Basic Statistical Details for Iris-setosa ---")
display(statistical_details.loc['setosa'])

print("\n--- Basic Statistical Details for Iris-versicolor ---")
display(statistical_details.loc['versicolor'])

print("\n--- Basic Statistical Details for Iris-virginica ---")
display(statistical_details.loc['virginica'])

--- Basic Statistical Details for Iris-setosa ---

sepal_length  count    50.000000
              mean      5.006000
              std       0.352490
              min       4.300000
              25%       4.800000
              50%       5.000000
              75%       5.200000
              max       5.800000
sepal_width   count    50.000000
              mean      3.428000
              std       0.379064
              min       2.300000
              25%       3.200000
              50%       3.400000
              75%       3.675000
              max       4.400000
petal_length  count    50.000000
              mean      1.462000
              std       0.173664
              min       1.000000
              25%       1.400000
              50%       1.500000
              75%       1.575000
              max       1.900000
petal_width   count    50.000000
              mean      0.246000
              std       0.105386
              min       0.100000
              25%       0.200000
              50%       0.200000
              75%       0.300000
              max       0.600000
Name: setosa, dtype: float64

--- Basic Statistical Details for Iris-versicolor ---

sepal_length  count    50.000000
              mean      5.936000
              std       0.516171
              min       4.900000
              25%       5.600000
              50%       5.900000
              75%       6.300000
              max       7.000000
sepal_width   count    50.000000
              mean      2.770000
              std       0.313798
              min       2.000000
              25%       2.525000
              50%       2.800000
              75%       3.000000
              max       3.400000
petal_length  count    50.000000
              mean      4.260000
              std       0.469911
              min       3.000000
              25%       4.000000
              50%       4.350000
              75%       4.600000
              max       5.100000
petal_width   count    50.000000
              mean      1.326000
              std       0.197753
              min       1.000000
              25%       1.200000
              50%       1.300000
              75%       1.500000
              max       1.800000
Name: versicolor, dtype: float64

--- Basic Statistical Details for Iris-virginica ---

sepal_length  count    50.000000
              mean      6.588000
              std       0.635880
              min       4.900000
              25%       6.225000
              50%       6.500000
              75%       6.900000
              max       7.900000
sepal_width   count    50.000000
              mean      2.974000
              std       0.322497
              min       2.200000
              25%       2.800000
              50%       3.000000
              75%       3.175000
              max       3.800000
petal_length  count    50.000000
              mean      5.552000
              std       0.551895
              min       4.500000
              25%       5.100000
              50%       5.550000
              75%       5.875000
              max       6.900000
petal_width   count    50.000000
              mean      2.026000
              std       0.274650
              min       1.400000
              25%       1.800000
              50%       2.000000
              75%       2.300000
              max       2.500000
Name: virginica, dtype: float64